apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-dispatch-service_vestfoldfylke_no
  fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
    target:
      kind: Application
      name: fint-flyt-dispatch-service

