fint:
  kafka:
    topic:
      org-id: fintlabs.no
    application-id: fint-flyt-dispatch-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-flyt-dispatch-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam