fint:
  org-id: fintlabs.no
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: flyt
    application-id: fint-flyt-dispatch-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-flyt-dispatch-service