apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ffk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-dispatch-service_ffk_no
  fintlabs.no/org-id: ffk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ffk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ffk.no"
    target:
      kind: Application
      name: fint-flyt-dispatch-service

